[WIP] HF loader addition
kraina-ai/srai pull request #430
Opened 2024-03-15 12:25 UTC by Repcak2000

2024-04-19 11:49 UTC, piotrgramacki requested changes
Feedback from meeting

2024-04-19 11:49 UTC, piotrgramacki commented on srai/datasets/_base.py
> +        data = HFLoader(os.environ["HF_access_token"]).load(dataset_name=dataset_name, name=name)
Move hf_token to parameter of the load function, and pass it from the outside

2024-04-19 11:49 UTC, piotrgramacki commented on pyproject.toml
> +    "mapclassify"
Leave only omegaconf and datasets here. Dotenv is not needed and last 3 are plotting related so we have it already included in extra "plotting"

2024-04-19 17:06 UTC, piotrgramacki requested changes
Some suggestions to make datasets easier to use and reuse with different datasets (not just ours)

2024-04-19 17:06 UTC, piotrgramacki commented on srai/datasets/philadelphia_crime.py
> +        self, hf_token: Optional[str] = None, dataset_version_name: str = "incidents_2023"
There is no information about where I can look for possible values for the parameter `dataset_version_name`. Maybe a link to the HF DatasetCard page in the class docstring would solve this?
Also, consider renaming this parameter. Maybe just `name` to keep compatibility with HF naming?

2024-04-19 17:06 UTC, piotrgramacki commented on srai/datasets/philadelphia_crime.py
> +        self, hf_token: Optional[str] = None, dataset_version_name: str = "incidents_2023"
There is no information about where I can look for possible values for the parameter `dataset_version_name`. Maybe a link to the HF DatasetCard page in the class docstring would solve this?
Also, consider renaming this parameter. Maybe just `name` to keep compatibility with HF naming?

2024-04-19 17:06 UTC, piotrgramacki commented on srai/loaders/hf_loader.py
> +            f"kraina/{dataset_name}", name=name, token=self.hf_token, trust_remote_code=True
Do not hardcode "kraina" here. This should be a part of "dataset_name"

2024-04-19 17:45 UTC, Calychas commented
Try to add tests to that

2024-04-19 19:04 UTC, Calychas requested changes

2024-04-19 20:07 UTC, Calychas commented
Note:
*change HFDataset to HuggingFaceDataset
* Better export the datasets so no ".dataset" is needed

2024-04-26 17:20 UTC, kacper-ki commented on srai/datasets/philadelphia_crime/dataset.py
> +    years_current: list[int] = [2020, 2021, 2022, 2023]
Are these needed at all?

2024-04-26 17:35 UTC, Calychas requested changes

2024-04-26 17:55 UTC, Calychas requested changes
Make sure that docs are added and example notebooks are generated there correctly.

Make hf datasets public and remove getting and setting the `hf_tokens` in the notebooks. (dont remove the functionality of passing the hf_token in the datasets)

Make `hf_token` and `version` parameters in load() in reverse order - `load(version, hf_token)`, not `load(hf_token, version)`. Update all the docstrings and usages

2025-10-08 14:21 UTC, RaczeQ commented
Implemented in #521

2025-10-08 14:21 UTC, closed without merging